### ISSUE TITLE
[action-manager][action-manager-ui] Duplicate key error in console

### ISSUE THREAD

**Issue by hvantran** [hvantran/project-management#43]

**Comment by hvantran** [comment]
```Warning: Each child in a list should have a unique "key" prop.

Check the render method of `PageRender`. See https://reactjs.org/link/warning-keys for more information.
    at Grid (http://localhost:3001/static/js/bundle.js:20714:87)
    at PageRender (http://localhost:3001/static/js/bundle.js:6911:31)
    at div
    at http://localhost:3001/static/js/bundle.js:8878:66
    at Grid (http://localhost:3001/static/js/bundle.js:37541:24)
    at ActionTrash (http://localhost:3001/static/js/bundle.js:3922:96)
    at RenderedRoute (http://localhost:3001/static/js/bundle.js:85314:5)
    at Routes (http://localhost:3001/static/js/bundle.js:85804:5)
    at div
    at http://localhost:3001/static/js/bundle.js:8878:66
    at Grid (http://localhost:3001/static/js/bundle.js:37541:24)
    at InnerThemeProvider (http://localhost:3001/static/js/bundle.js:37607:70)
    at ThemeProvider (http://localhost:3001/static/js/bundle.js:37118:5)
    at ThemeProvider (http://localhost:3001/static/js/bundle.js:37626:5)
    at App
    at Router (http://localhost:3001/static/js/bundle.js:85742:15)```

**Comment by hvantran** [comment]
action-manager


![Image](https://github.com/hvantran/project-management/assets/17746024/de1bf133-7148-485a-9391-c139f3eb8251)
